# Generated by Django 4.0.1 on 2022-01-15 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('date_booking', models.DateField()),
                ('phone', models.IntegerField()),
                ('email', models.TextField()),
            ],
        ),
    ]
